### ISSUE TITLE
Pop-Up window doesn't disappear

### ISSUE THREAD

**Issue by Francesco-Manni** [steam3d/MagicPods-Windows#102]
I have an issue with the pop-up window not disappearing. It stays on the screen until I close it manually. I'm not sure if this is happening to other users too.

**Comment by steam3d** [comment]
Hi. It happens when you interact too quickly with headphones. The Windows does not have time to receive commands from the headphones. You can try with iPhone it has the similar behavior.  I tested many times, for me the animation doesn't disappear 1/30 of the time. Also, if you open the case more that couple minutes animation may not disappear.

**Comment by M3L0nDev** [comment]
Yeah it happened to me recently too. I've been using my AirPods Pro the same way since the start and there wasn't such issue when I first installed MagicPods. Not sure what caused this issue all of a sudden. And it's quite often

**Comment by steam3d** [comment]
@M3L0nDev To add supports AirPods Max It was necessary to completely change the animation window hiding algorithm. Now it is almost like on the iPhone. iPhone also does not always hide animation. 
Try to open and close the case, insert and remove the earphone from the case. Does the window disappear?

**Comment by steam3d** [comment]
https://github.com/steam3d/MagicPods-Windows/issues/104
