### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by wulanren** [steam3d/MagicPods-Windows#14]
I am a Chinese user, and I have no Chinese option when using the software, so it is difficult to use

**Comment by Alvis-is-coding** [comment]
Setting == 设置
  Ear detection == 耳朵检测/入耳检测/佩戴检测
    One airpods out of ear == 当一只airpods离开耳朵时/当一只airpods被摘下时
      Play/Pause == 播放/暂停 （播放暂停目前支持部分浏览器和播放器）
      Decrease volume （by 75%）== 降低(75%的)音量
      Both(Decrese volume + Play/Pause) == 同时（降低音量 + 播放/暂停）
      None == 无（操作）
  Search Airpods == 搜索Airpods
    Max == 最大强度
    Min == 最小强度
    Live signal == 活动信号（正常工作时的信号强度）
    Fast search == 快速搜索（Airpods）（减少搜索Airpods所需的时间，当你确信附近没有其他人使用Airpods时再启用这个功能）
  Animation == （弹窗）动画
    Airpods splash screen == Airpods 闪屏（弹窗动画）（当你打开电池仓时，像iPhone一样显示Airpods弹窗。如果弹窗动画不能正常显示，将后面的Signal值设置为上方“搜索Airpods”设置区域中 “活动信号” 你观测到的平均值（大致值））
    Splash screen size == 弹窗动画大小
  System Tray == 系统托盘（图标）
    Hide tray icon == 隐藏托盘图标（应用重启后生效）
    Show Airpods battery on tray icon == 在托盘图标中显示Airpods电量（每分钟更新）

**Comment by steam3d** [comment]
Hi, can you fill a google sheet?
https://github.com/steam3d/MagicPods-Windows/issues/23

**Comment by Alvis-is-coding** [comment]
Hi,

I saw the latest update. Thank you for your devotion. But there existed some embarrassing translation. I only finished about half of the “zh-CN”column of the google sheet due to my bad network condition. As I reopened it on another day, it was filled completely.

I adjusted some pieces of translation 10 hours before. It may be better to replace those for next update. Sorry for the trouble.

Best regards,
Alvis

发件人: Alexander Maslov<mailto:notifications@github.com>
发送时间: 2020年7月22日 21:28
收件人: steam3d/MagicPods-Windows<mailto:MagicPods-Windows@noreply.github.com>
抄送: Alvis-is-coding<mailto:anbrilex2cyo@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [steam3d/MagicPods-Windows] Language (#14)


Hi, can you fill a google sheet?
#23<https://github.com/steam3d/MagicPods-Windows/issues/23>

―

**Comment by steam3d** [comment]
You can change text if you think that it will be better. Mark changed cell with some color maybe yellow. It impossible for me understand changes with Chinese, Japan or Arabic.  I just copy text without any correction.

Some people here https://github.com/steam3d/MagicPods-Windows/issues/23 already suggested their translation

**Comment by Alvis-is-coding** [comment]
Ok, I have changed all my “Airpods” or “airpods” text to the Apple official “AirPods”. I’ll mark them later for you.

________________________________
发件人: Alexander Maslov <notifications@github.com>
发送时间: Monday, July 27, 2020 4:47:45 PM
收件人: steam3d/MagicPods-Windows <MagicPods-Windows@noreply.github.com>
抄送: Alvis-is-coding <anbrilex2cyo@outlook.com>; Comment <comment@noreply.github.com>
主题: Re: [steam3d/MagicPods-Windows] Language (#14)


You can change text if you think that it will be better. Mark changed cell with some color maybe yellow. It impossible for me understand changes with Chinese, Japan or Arabic. I just copy text without any correction.

Some people here #23<https://github.com/steam3d/MagicPods-Windows/issues/23> already suggested their translation

―

**Comment by steam3d** [comment]
I already changed “Airpods” or “airpods” to “AirPods”. The google sheets contains the all corrections from all participants in the translation

**Comment by Alvis-is-coding** [comment]
Cool.

发件人: Alexander Maslov<mailto:notifications@github.com>
发送时间: 2020年7月27日 17:02
收件人: steam3d/MagicPods-Windows<mailto:MagicPods-Windows@noreply.github.com>
抄送: Alvis-is-coding<mailto:anbrilex2cyo@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [steam3d/MagicPods-Windows] Language (#14)


I already changed “Airpods” or “airpods” to “AirPods”. The google sheets contains the all corrections from all participants in the translation

―

**Comment by steam3d** [comment]
@wulanren Added. Update to 1.0.37.0
