### ISSUE TITLE
Won't connect with my airpods

### ISSUE THREAD

**Issue by Shoghy** [steam3d/MagicPods-Windows#157]
Simply that, when I connect my airpods to bluetooth, the program starts looking for the airpods, but ends up saying "infinite search". Tried all 3 solutions you have on the page, but none solved the problem.

[error.zip](https://github.com/steam3d/MagicPods-Windows/files/7722688/error.zip)

**Comment by steam3d** [comment]
Hi. I checked the log files. The problem is Bluetooth drivers issue or Bluetooth dongle is incompatible.
On my part, I can’t do anything. You can try to install Bluetooth drivers of different versions, maybe some of them will work.

If you have other bluetooth devices connected you can try to disconnect them.

**Comment by steam3d** [comment]
No feedback
