### ISSUE TITLE
Audio quality when voice call in Discord is much lower

### ISSUE THREAD

**Issue by RadianMay** [steam3d/MagicPods-Windows#199]
I have a problem where when I start or join a voice call in Discord the audio quality of AirPods is much lower. I believe this is caused by windows switching to the headset instead of the headphone profile for bluetooth audio devices. Is there a way to force windows to use the higher quality headphone profile for audio via MagicPods, as I don't see this option.

Previously when I connected my airpods directly to windows, there would be two audio profile settings which I could manually choose from, but after installing MagicPods I only see one, which does not allow me to choose.

**Comment by steam3d** [comment]
Hi. I first of all the MagicPods does not change audio settings. It just switch between selected audio endpoint and AirPods.
If you have the windows 11 your described behavior is expected. Because windows 11 change the way to switch between headset and headphones. The windows decide without you opinion which audio service choose.  

If you have external microphone you can just turn off the headset service.

You can find setting to do it here 
https://help.magicpods.app/issue-connectivity/
