### ISSUE TITLE
airpods can't connect magic pods

### ISSUE THREAD

**Issue by jackobrien22** [steam3d/MagicPods-Windows#243]
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/9483567/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9483568/MagicPodsServiceLog.txt)

I need help

**Comment by steam3d** [comment]
Hi. What's wrong? Can you describe your issue?

**Comment by jackobrien22** [comment]
![184495945-297a5197-a99b-42b1-b2b7-27ca20db9304](https://user-images.githubusercontent.com/112785942/188309821-9d969280-4f4b-4ca4-82c5-d73b05b2b267.png)

same problem

**Comment by steam3d** [comment]
I can't do anything from my side because the issue does not related to MagicPods.  The MagicPods does not receive any data from Windows Bluetooth, so your Windows has some trouble with Bluetooth LE or some settings block the Bluetooth usage for other apps.

To important steps that helped many users
1. Update Bluetooth driver manually. (Go to Bluetooth manufacture site, download the newest Bluetooth driver and install it)
2. The fake AirPods does not support.

**Comment by steam3d** [comment]
No feedback
