### ISSUE TITLE
Can't connect/disconnect using the app

### ISSUE THREAD

**Issue by ghost** [steam3d/MagicPods-Windows#244]
To connect and disconnect I have to go though Windows settings.

**Comment by POPPI29** [comment]
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/9526513/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/9526514/MagicPodsUILog.txt)
Dunno if these are the ones

**Comment by steam3d** [comment]
Everything right. The MagicPods gets nothing when asked from Windows audio devices. So because of it the connection option does not works. 

You can try to recreate the audio devices:

1. Turn off the MagicPods
2. Disable headset and headphones 4.Enable headset and headphones
5. Run MagicPods
https://help.magicpods.app/issue-connectivity/
