### ISSUE TITLE
MagicPods and windows bluetooth all connected, but no any sound.

### ISSUE THREAD

**Issue by Jimmy-506** [steam3d/MagicPods-Windows#267]
I heard the connecting beep. 
MagicPods and windows bluetooth all connected, but no any sound.

My device is Airpods 3.

[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/10137656/MagicPodsServiceLog.txt)
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/10137657/MagicPodsUILog.txt)

**Comment by steam3d** [comment]
Hi.  Windows controls Bluetooth connection disconnection and processing audio, so this issue is not connected with MagicPods.

You must be sure that:
1. AirPods connected and audio services also connected
![image](https://user-images.githubusercontent.com/30986874/205240462-acc7bb72-a34d-4207-8efa-bad256108a63.png)
2. Audio output switch to AirPods 
![image](https://user-images.githubusercontent.com/30986874/205240835-110a4833-2b9f-422b-a491-2613c5d6c0ea.png)
3. Sound is not mute. Because it's hard to understand, as only the icon changes, but the volume remains the same
![image](https://user-images.githubusercontent.com/30986874/205240971-af534aa0-45a3-4aee-916e-a5fc8540bbf4.png)
4. AirPods must have enabled at least Audio Sink service. https://help.magicpods.app/issue-connectivity/
![image](https://user-images.githubusercontent.com/30986874/205241341-e96af378-315c-46a7-bac0-abd5a501db2f.png)
