### ISSUE TITLE
Can't adjust the volume on headphones

### ISSUE THREAD

**Issue by AVKozlovskyi** [steam3d/MagicPods-Windows#279]
Can't adjust the volume on headphones
Apple AirPods 2

**Comment by steam3d** [comment]
Hi. This issue is not related to MagicPods. Bluetooth driver control key behavior of Bluetooth headphones. In headset mode volume can change but Windows UI will show always 100%. 
To enable or disable master volume read here:
https://www.reddit.com/r/airpods/comments/b6l5bm/airpods_2_windows_10_max_volume_fix/

It all information that I have.
