### ISSUE TITLE
Seperate connect/disconnect keys to two buttons.

### ISSUE THREAD

**Issue by bigplayer-ai** [steam3d/MagicPods-Windows#287]
Hey,
Can you seperate connect/disconnect keys to two buttons? 
Sometimes my magicpods is stuck but I want it to connect and not disconnect to airpods pro.
EDIT: Sorry for being unclear. It is more of a reliability feature request.
I meant stuck on connected/disconnected/connecting (connection status) of the AirPods. So, if you separate the button with the if statement (or any other solution you got), this would help a lot when trying to connect to my AirPods.

**Comment by steam3d** [comment]
Hi.  Could you describe how MagicPods "stuck"?

The keys can't be separate because it does not have any sense.  Connect and disconnect depends from headphone connection state. So if there are separated keys for connect and disconnect it will act the same as current implementation.

**Comment by steam3d** [comment]
If MagicPods is stuck - the hotkeys will not works as other functions, but I never get MagicPods is stuck.

**Comment by bigplayer-ai** [comment]
Sorry for being unclear. I meant stuck on connected/disconnected(connection status) of the AirPods.So if you separate the buttons with if statement this would help a lot when trying to connect to my AirPods.On 6 Jan 2023, at 13:02, Alexander Maslov ***@***.***> wrote:﻿
If MagicPods is stuck - the hotkeys will not works as other functions, but I never get MagicPods is stuck.

**Comment by bigplayer-ai** [comment]
> Sorry for being unclear. It is more of a reliability feature request. I meant stuck on connection status (connected/disconnected/connecting/disconnecting) of the AirPods. So, if you separate the button with the if statement (or any other solution you got), this would help a lot when trying to connect to my AirPods.

@steam3d is this an enhancement?

**Comment by steam3d** [comment]
Well, when you press shortcut the connection process begin. You will see the gear icon in system tray. The process can took between 1 and 10 seconds. If something wrong - you will get notification.

If the MagicPods stuck some how on connecting state - it is critical failure.  Even if the MagicPods has different key for connect and disconnect you could not do that because app will not react on it. (This is theoretical, because I have not met such a problem)

Usually you will get always error notification if connection failed. Restart application may help.


The Windows has hard coded ability to reconnect disconnected devices. If you disconnected devices using Windows settings, It will be reconnected after 15-60 sec by unknown reason. MagicPods also has such behavior because Windows manages connection.

**Comment by steam3d** [comment]
Added. Update to 2.0.78.0.
