### ISSUE TITLE
MagicPods causes computer to crash when set as a startup app

### ISSUE THREAD

**Issue by RadianMay** [steam3d/MagicPods-Windows#301]
Hello,

I found that MagicPods causes my computer to crash after resuming from sleep after it is configured to automatically open on startup. For some reason when it is set to not open as a startup app this behaviour does not appear to happen.

**Comment by steam3d** [comment]
Hi. When you setup the startup task the Windows will run the MagicPods when you turn on the PC, so when you send your PC to sleep or wake it up the startup task will not execute.

You could try to [check system files](https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e) and upload the log files from MagicPods.

I am not sure that the startup task was cause of your computer to crash, because you are the first person who have such issue for 3 years and logic of this startup task wasn't changed since.
