### ISSUE TITLE
Audio streaming stutters

### ISSUE THREAD

**Issue by alejandro5042** [steam3d/MagicPods-Windows#336]
Experiencing a lot of sutter listening to a podcast from my iPhone, and streaming it to my PC using the "Audio streaming" feature.

HW requirements are definitely not an issue here (32 cores, 128 GB RAM, etc), with <5% CPU usage.

What could be going on? A buffering issue with the app?

**Comment by steam3d** [comment]
Hi. Everything works right on your PC.  It's common Bluetooth Classic behavior when use multiple connections. By my test I notised that Bluetooth Bandwidth or Transmitter Power can effect. 

My iPhone also has stutters  sometimes, but on Samsung I never gut  any stutters.

**Comment by wsy** [comment]
I have the same issue.
MyPC: Core i7 6700k, 32GB RAM, and Intel AX200.
Device: AirPods Pro, Sony XR-55X90J TV

Step1:
When I connected AirPods Pro to my PC, everything was working.

Step2:
When I started streaming from my Sony TV to my PC,
audio began to stutter.

Step3:
I stopped streaming from my Sony TV to my PC.
If it were caused by Bluetooth bandwidth issue, audio stuttering issue should be gone by now.
However, the sound in my AirPods Pro still stutters.

Step4:
I disconnect and recconnect my AirPods Pro, everything works again.

**Comment by steam3d** [comment]
@wsy The Bluetooth driver manages connections. I do not have access directly to Bluetooth driver, therefore, this is not a problem, but a feature of the operation of a specific Bluetooth driver.

For my part, I can’t do anything, but you can safely share your opinions and possible solutions to the driver’s operation.

**Comment by wsy** [comment]
OK. now I understand.

1. This is caused by the Bluetooth bandwidth issue.
2. It's the driver's behavior that my AirPods Pro remains stuttering after I stopped streaming from my TV to my PC.

Is this correct?

By the way, I'm curious: When you developed this feature, what configuration did you use? Did you come across this audio-stutter issue?

**Comment by steam3d** [comment]
@wsy when I used on PC everything was fine, but when I switch to laptop the audio-stutter began. The way to resolve issue - create custom Bluetooth driver and reduce audio quality.

You could also switch to internal speaker and back to AirPods, it will force the Bluetooth driver to update audio channel, it could remove audio-stutter without disconnecting AirPods.
