### ISSUE TITLE
How to have high quality audio and mic Airpods (non-pro) gen 2

### ISSUE THREAD

**Issue by pixelstoriez** [steam3d/MagicPods-Windows#363]
I've read other issues but all the solutions are for a specific dongle that I do not use, my PC has a built-in Bluetooth 5.3 Wifi card, is there any universal fixes? I am also looking to buy a Airpods Pro gen 2 soon, do they have the same issue too?

**Comment by steam3d** [comment]
No, you can only get bad microphone quality instead of terrible using special Bluetooth dongle and special driver. The version Bluetooth does not effect on audio quality. It applies on any Bluetooth headphones. The Bluetooth hands-free profile was designed like this many years ago. The best solution to get good microphone quality is buy a wired microphone.
