### ISSUE TITLE
airpods pro2 （USB-C）2023

### ISSUE THREAD

**Issue by Hal-Git-Castle** [steam3d/MagicPods-Windows#380]
Hello, the program may have some problems with the new version of AirPods pro2 support:
1. After taking off the earphones, the audio cannot be automatically paused.
2. When iPhone and Windows are connected at the same time, the audio cannot be switched to each other, you need to manually close the connection of Windows
3. The pop-up window responds very slowly

iOS：17.1
Windows：11
AirPods firmware version：6A305

**Comment by Hal-Git-Castle** [comment]
Sorry, I may not have made it clear.
1. What to check? Is it configuration?
2. I can't connect iPhone and Windows at the same time, when connecting one, the other will be interrupted. What could be the reason for this?

![1699350346831](https://github.com/steam3d/MagicPods-Windows/assets/126157013/a082b575-e838-486b-aa67-fd45af8cd00e)

**Comment by steam3d** [comment]
1. Apple has restricted AirPods Pro 2 to work on non-Apple devices. Ear detection is not available for AirPods Pro 2.
![image](https://github.com/steam3d/MagicPods-Windows/assets/30986874/7f6c55da-fd7b-4e97-8c74-634042e4e5df)
2. Yes, you can't, because that's how Bluetooth headphones work. You can use Bluetooth headphones only with one device at the same time.  But you could try to stream audio from iPhone to Windows and connect AirPods to Windows.

**Comment by steam3d** [comment]
Implemented on MagicPods 2.0.72.0. [MagicAAP driver required](https://help.magicpods.app/fun-magicaap/)
To discuss, join [MagicPods Discord](https://discord.com/invite/UyY4PY768V)
