### ISSUE TITLE
Log for WF-1000XM3

### ISSUE THREAD

**Issue by Shua131** [steam3d/MagicPods-Windows#47]
Put the log in my previous issue but thought it would be easier to find if I put it in its own issue.
[log.txt](https://github.com/steam3d/MagicPods-Windows/files/5632875/log.txt)

**Comment by steam3d** [comment]
I saw your log. The main thing is WF-1000XM3 works other way. It require write large piece of code to add support WF-1000XM3. For example almost all Apple devices work the same way, because of that it is easy to add other type of AirPods.
In you case is possible to add support WF-1000XM3 but it is impossible to write the program without WF-1000XM3.

**Comment by Shua131** [comment]
Oh, ok

**Comment by steam3d** [comment]
Attach to https://github.com/steam3d/MagicPods-Windows/issues/21
