### ISSUE TITLE
translation for Microsoft Store and a question

### ISSUE THREAD

**Issue by Sheey11** [steam3d/MagicPods-Windows#68]
Microsoft do not put apps which haven't localized on the first place of search result, it took me some while finding MagicPods.  
Here's Chinese Simplified translation

- Introduction
 I have deleted the dark mode and "battary is displayed with interval 10%", because it's unnecessary in introduction.
  > MagicPods 带来了与 iOS 相媲美的 AirPods 使用体验。
  > 和 iPhone 一样，MagicPods 能在打开充电盒时弹出连接提示，也能通过入耳检测自动暂停和播放视频和音频，位于任务栏的图标指示了 AirPods 的电量。MagicPods 还能在以后自动连接 AirPods！
  > 注意：你需要拥有支持蓝牙 4.0 或以上版本的硬件。
- Features
  > MagicPods 支持 AirPods 第一代和第二代、AirPods Pro 和 PowerBeats Pro。
  > MagicPods 支持与 iOS 或 Mac 类似的入耳检测。
  > 实时查看 AirPods 和充电盒的电量。
  > 在打开充电盒时播放动画。
  > App 内支持黑暗模式。
  > 低电量警告。
  > 自动连接 AirPods（尚在测试中）。

---

Is it possible to override the pause action of AirPods (press for AirPods Pro)? Because I found that the in-ear detection and pause action act differently.  
e.g. I opened a video in Chrome, and a music software. The in-ear detection pauses the music software, but the manual pause action pauses the video.

**Comment by steam3d** [comment]
1.
Hi. I want remap buttons too. The problem is that pause button on keyboard and pause button on AirPods for windows it is the same button. Windows map all media keys as one device. If I change the pause button to next button this applies to both the keyboard and headphones. I did not find another way.

Of course i can just remap the default pause to my custom pause. But i think it wrong solution.

2.
Store also have search words. I added search words on Russian and English languages.
Search words like this:
"Connect AirPods"
"Battery AirPods"
"App for AirPods"
"AirPods windows battery level"

it might be worth adding Microsoft Store description to `weblate` to other people can translate if they want.

**Comment by Sheey11** [comment]
thx, I will keep an eye on weblate.

**Comment by steam3d** [comment]
I also need a translation of these words. So that I can finish the description:
- Add a little magic to your AirPods.  
- AirPods battery
- AirPods Pro battery
- PowerBeats battery
- Connect AirPods
- Connect AirPods Pro
- Connect PowerBeats

**Comment by Sheey11** [comment]
- 向您的 AirPods 添加一点魔法
- AirPods 电量
- AirPods 电量
- PowerBeats 电量
- 连接 AirPods
- 连接 AirPods Pro
- 连接 PowerBeats
- 蓝牙电量 ( Or I thought it should be `Bluetooth headset battery` -> `蓝牙耳机电量`)

**Comment by steam3d** [comment]
Thx. I uploaded the latest version 1.0.61.0 that include those changes.
