### ISSUE TITLE
Enhancement: Workaround for better audio and mic quality

### ISSUE THREAD

**Issue by hchavan-cmd** [steam3d/MagicPods-Windows#82]
This should be a known issue I believe. Windows does not support streaming input and output of high-quality audio (over A2DP) while using BT. Handsfree profile is abysmal and is barely even audible. I have heard there are hacks to force Windows into allowing this, as it doesn't seem to be a bandwidth issue with the BT card necessarily. Are there any such plans in development (or the near future) as Apple headphones especially struggle with it, using AAC rather than APTX?

**Comment by steam3d** [comment]
Hi. Unfortunately, this can't be done. Because needs to write a driver to each Bluetooth module that which implements profile "Bluetooth Headset Helper". 
You can read about it [here]( https://www.reddit.com/r/airpods/comments/7gdvma/airpods_bluetooth_drivers_for_windows_10/). 

Note. The MagicPods can't work with two Bluetooth modules, there are huge problem with right detect main Bluetooth module.

**Comment by hchavan-cmd** [comment]
Ahh yes, alright. Understandable. Just to add to this, I really want to but the app right now, but Microsoft store is acting up and not letting me make the payment. :(

**Comment by steam3d** [comment]
You can write to MagicPods@outlook.com with your username on GitHub in the title

**Comment by hchavan-cmd** [comment]
Thanks! :)
