### ISSUE TITLE
Battery info page show only battery percentage (Airpods Pro)

### ISSUE THREAD

**Issue by byrdxxiii** [steam3d/MagicPods-Windows#91]
![image](https://user-images.githubusercontent.com/82694163/115102222-a4362780-9f73-11eb-9c47-3ae4d065c3bd.png)

**Comment by steam3d** [comment]
Hi. Can you send a log file? Did the video show before?
What did you try to do?

**Comment by byrdxxiii** [comment]
Hello, I didn't do anything but a picture of airpods pro doesn't show in UI since I downloaded the app (pop-up animation is work fine), so I already uninstall and reinstall but it's doesn't fix my problem.

here some log files :
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/6329214/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/6329215/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Open `Support` page.  Click on logo 5-10 time while until the page refresh, the go to `General settings`, scroll down and switch `Log level` to debug. The close MagicPods window.

After that connect to AirPods and open the `status` page without video. Extra data will write to log file. You will need to upload log here.

I'm using a standard video player from Windows, there is a high probability that the problem is related to Windows. Possible with video card driver.

**Comment by byrdxxiii** [comment]
[MagicPodsUILog.txt](https://github.com/steam3d/MagicPods-Windows/files/6329915/MagicPodsUILog.txt)
[MagicPodsServiceLog.txt](https://github.com/steam3d/MagicPods-Windows/files/6329916/MagicPodsServiceLog.txt)

**Comment by steam3d** [comment]
Did you try update video driver? According the log file everything fine.  The video player made Microsoft, i cannot influence him.

**Comment by steam3d** [comment]
No feedback
